<a href="https://colab.research.google.com/github/Sk1nder/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.2'

Funkcje

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__annotations__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

## 1D Array

In [6]:
x = np.array([1, 3])
x

array([1, 3])

In [7]:
print(x)

[1 3]


In [9]:
len(x)

2

In [10]:
x.shape

(2,)

In [11]:
x.ndim

1

In [12]:
x.size

2

In [13]:
x.dtype

dtype('int64')

In [14]:
np.array([2.1, 3.2, 3.4])

array([2.1, 3.2, 3.4])

## 2D Array


In [20]:
y = np.array([[1,2],[3,4]])

In [21]:
y.ndim

2

In [22]:
len(y)

2

In [23]:
y.shape

(2, 2)

In [24]:
y.dtype

dtype('int64')

In [26]:
d2 = np.array([[1,2,3],[4,5,6]])

In [27]:
d2.shape

(2, 3)

## 3D Array

In [28]:
x3 = np.array([[
    [1,2,3],
    [3,4,5]],

    [[5,6,7],
     [8,7,9]]
               ])
x3

array([[[1, 2, 3],
        [3, 4, 5]],

       [[5, 6, 7],
        [8, 7, 9]]])

In [30]:
x3.shape

(2, 2, 3)

In [31]:
len(x3)

2

In [33]:
x3.ndim

3

## Typy danych

In [34]:
A = np.array([3.2, 3., 5.1])
A

array([3.2, 3. , 5.1])

In [35]:
A.dtype

dtype('float64')

In [36]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [37]:
A

array([1., 2., 3.])

In [39]:
A = np.array([3.7, 3., 5.1], dtype='int')
A

array([3, 3, 5])

In [41]:
A = np.array([True, False], dtype='bool')
A

array([ True, False])

In [42]:
A.dtype

dtype('bool')

In [43]:
A = np.array([24, 120, 230], dtype=np.int8)
A.dtype

<ipython-input-43-27ab11b0e872>:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 230 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  A = np.array([24, 120, 230], dtype=np.int8)


dtype('int8')

In [44]:
A

array([ 24, 120, -26], dtype=int8)

In [45]:
A = np.array([24, 120, 230], dtype=np.uint8)
A

array([ 24, 120, 230], dtype=uint8)

## Tworzenie tablic

In [46]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [48]:
np.full(shape=(3,3), fill_value=4, dtype=float)

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [52]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [50]:
np.arange(1,101,1).reshape((10,10))

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [53]:
np.linspace(start=1, stop=2, num=11)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [54]:
A = np.arange(15)

In [55]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
A.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [58]:
A.reshape((-1, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## Operacje na tablicach

In [59]:
A = np.array([3, 1, 5, 6])
B = np.array([5, 7, 2, 5])

In [60]:
A + B

array([ 8,  8,  7, 11])

In [61]:
A - B

array([-2, -6,  3,  1])

In [62]:
A * B

array([15,  7, 10, 30])

In [64]:
A/B

array([0.6       , 0.14285714, 2.5       , 1.2       ])

In [66]:
A + 1

array([4, 2, 6, 7])

In [67]:
B/2

array([2.5, 3.5, 1. , 2.5])

In [69]:
B**A

array([  125,     7,    32, 15625])

In [70]:
np.add(A, B)

array([ 8,  8,  7, 11])

In [71]:
np.subtract(A, B)

array([-2, -6,  3,  1])

In [72]:
np.multiply(A, B)

array([15,  7, 10, 30])

In [73]:
np.divide(A, B)

array([0.6       , 0.14285714, 2.5       , 1.2       ])

In [63]:
A.dot(B)

62

In [65]:
B.dot(A)

62

In [75]:
np.dot(A, B)

62

In [76]:
X = np.array([[1, 3],[-2, 0]])
Y = np.array([[6, 0],[-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [77]:
X*Y

array([[6, 0],
       [2, 0]])

In [78]:
np.dot(X,Y)

array([[  3,   6],
       [-12,   0]])

In [79]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [80]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [81]:
X @ Y

array([[  3,   6],
       [-12,   0]])

## Generowanie liczb pseudolosowych

In [82]:
np.random.seed(0)

Rozkład normalny np.random.randn()

In [83]:
np.random.randn()

1.764052345967664

In [84]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [86]:
np.random.randn(10,5)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462, -1.45436567],
       [ 0.04575852, -0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218, -0.4380743 ],
       [-1.25279536,  0.77749036, -1.61389785, -0.21274028, -0.89546656],
       [ 0.3869025 , -0.51080514, -1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117, -0.67246045]])

Rozkład z przedziału jednostajnego

In [87]:
np.random.rand()

0.317983179393976

In [88]:
np.random.rand(10, 2)

array([[0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609],
       [0.18319136, 0.58651293],
       [0.02010755, 0.82894003],
       [0.00469548, 0.67781654]])

In [89]:
np.random.randint(10)

3

In [91]:
np.random.randint(low=10, high=101)

23

In [92]:
np.random.randint(low=10, high=101, size=10)

array([50, 82, 29, 82, 36, 76, 62, 77, 71, 24])

In [94]:
np.random.randint(low=10, high=101, size=(10,2))

array([[14, 77],
       [21, 96],
       [87, 85],
       [66, 26],
       [34, 39],
       [31, 35],
       [90, 70],
       [71, 93],
       [43, 42],
       [80, 95]])

In [97]:
np.random.choice(np.random.randint(low=10, high=101, size=(10))) #losowanie z listy

93

In [98]:
data = np.arange(10)

In [101]:
np.random.shuffle(data) #zapisuje w zmiennej od razu - bez parametru inplace

In [102]:
data

array([4, 6, 9, 1, 3, 5, 0, 8, 7, 2])

## Podstawowe funkcje w bibliotece NumPy

In [105]:
np.exp(1) #funkcja wykładnicza

2.718281828459045

In [106]:
np.sqrt(9) #pierwiastek

3.0

In [108]:
np.all([2, 3, 1]) #iteruje po argumentach i zwraca True/False

True

In [109]:
np.all([2, 3, 0]) #iteruje po argumentach i zwraca True/False

False

In [111]:
np.any([2, 3, 0]) #iteruje po argumentach i zwraca True/False

True

In [113]:
np.any([0, 0]) #iteruje po argumentach i zwraca True/False

False

In [115]:
A = np.random.rand(5)
A

array([0.17949026, 0.1709866 , 0.46345098, 0.87457296, 0.94411975])

In [119]:
A.argmax() # pozycja wartości największej

4

In [117]:
A[4]

0.9441197509175635

In [118]:
A.max()

0.9441197509175635

In [121]:
B = np.random.rand(5, 2)
B

array([[0.75084425, 0.96448977],
       [0.55424244, 0.2123905 ],
       [0.22244322, 0.21874937],
       [0.56957353, 0.45210904],
       [0.97023668, 0.68054469]])

In [122]:
B.argmax()

8

In [124]:
B.max()

0.9702366830961006

In [127]:
np.median(B)

0.5619079848295891

In [129]:
np.std(A) #odchylenie standardowe

0.33055763614851075

## Indeksowanie / Wycinanie

In [130]:
# A[idx], A[start:stop], A[start:]

In [136]:
A = np.arange(1,21)

In [143]:
A = A.reshape((4,5))
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [141]:
A[0]

array([1, 2, 3, 4, 5])

In [142]:
A[:,0]

array([ 1,  6, 11, 16])

In [145]:
A[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [146]:
A[2,2]

13

In [147]:
A[1:3,2:4]

array([[ 8,  9],
       [13, 14]])

In [149]:
A[1, 2] =14
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7, 14,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Iteracja po tablicach / zmiana rozmiaru / maski logiczne

In [150]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7, 14,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [152]:
for row in A:
  print(row)

[1 2 3 4 5]
[ 6  7 14  9 10]
[11 12 13 14 15]
[16 17 18 19 20]


In [153]:
for item in A.flat:
  print(item)

1
2
3
4
5
6
7
14
9
10
11
12
13
14
15
16
17
18
19
20


In [155]:
A.shape

(4, 5)

In [156]:
A.reshape(2, -1)

array([[ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [158]:
A.ravel() #do 1D

array([ 1,  2,  3,  4,  5,  6,  7, 14,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [159]:
A.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3, 14, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [161]:
A.flat

In [162]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [165]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [166]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [167]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [169]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [170]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [173]:
np.bitwise_or(A < 5, A > -5)
A[np.bitwise_or(A < 5, A > -5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])